import{a as f,i,S as y}from"./assets/vendor-CA5bdUtC.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const b="45161707-c900d4c58d729c828a58b7932",E="https://pixabay.com/api/";document.querySelector(".js-loader");const g=document.querySelector(".js-loader-more");function L(){g.style.display="flex"}function P(){g.style.display="none"}async function m(s,n=1){const t=new URL(E);t.searchParams.set("key",b),t.searchParams.set("q",s),t.searchParams.set("image_type","photo"),t.searchParams.set("orientation","horizontal"),t.searchParams.set("safesearch","true"),t.searchParams.set("page",n),t.searchParams.set("per_page",15),L();try{const o=await f.get(t.toString());if(o.status!==200)throw new Error("Network response was not ok");return o.data}catch(o){throw console.error("Error fetching images:",o),i.error({title:"Error",message:"Failed to fetch images.",position:"topRight"}),o}finally{P()}}const w=document.getElementById("gallery");let h;function p(s){if(s.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const n=s.map(({webformatURL:t,largeImageURL:o,tags:e,likes:r,views:a,comments:c,downloads:l})=>`
      <a href="${o}" class="gallery-item">
        <img src="${t}" alt="${e}" />
        <div class="info gallery-text-list">
          <p class="info-item"><b>Likes:</b> ${r}</p>
          <p class="info-item"><b>Views:</b> ${a}</p>
          <p class="info-item"><b>Comments:</b> ${c}</p>
          <p class="info-item"><b>Downloads:</b> ${l}</p>
        </div>
      </a>
    `).join("");w.insertAdjacentHTML("beforeend",n),h?h.refresh():h=new y(".gallery a",{captionsData:"alt",captionDelay:250})}document.addEventListener("DOMContentLoaded",()=>{const s=document.getElementById("searchInput"),n=document.getElementById("searchForm"),t=document.getElementById("gallery"),o=document.getElementById("loadMoreButton");let e=1,r="",a=0;const c=s.getAttribute("placeholder");s.addEventListener("focus",()=>{s.setAttribute("data-placeholder",c),s.setAttribute("placeholder","")}),s.addEventListener("blur",()=>{s.setAttribute("placeholder",c)}),n.addEventListener("submit",async l=>{l.preventDefault();const d=s.value.trim();if(d===""){i.error({title:"Error",message:"Please enter a search term.",position:"topRight"});return}t.innerHTML="",r=d,e=1,o.style.display="none";try{const u=await m(r,e);a=u.totalHits,u.hits.length===0?i.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(i.success({title:"Success",message:`Found ${a} images.`,position:"topRight"}),p(u.hits),o.style.display=t.children.length<a?"block":"none")}catch{i.error({title:"Error",message:"Failed to fetch images.",position:"topRight"})}s.value=""}),o.addEventListener("click",async()=>{e+=1;try{const l=await m(r,e);p(l.hits),t.children.length>=a&&(o.style.display="none",i.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const{height:d}=t.firstElementChild.getBoundingClientRect();window.scrollBy({top:d*2,behavior:"smooth"})}catch{i.error({title:"Error",message:"Failed to fetch images.",position:"topRight"})}})});
//# sourceMappingURL=commonHelpers.js.map
